### ISSUE TITLE
还是pod的问题

### ISSUE THREAD

**Issue by miku1958** [Insfgg99x/FGReverser#2]
pod的时候reverse不是直接放在mainBundle下的,而是放在mainBundle下的Frameworks/FGReverser.framework/reverse
可以改为
- (NSDictionary *)mapper {
    if(!self.reverseMap) {
        NSString *mapPath = [NSBundle.mainBundle  pathForResource:@"reverse" ofType:nil];
        if(!mapPath.length){
                mapPath = [NSBundle.mainBundle pathForResource:@"Frameworks/FGReverser.framework/reverse" ofType:nil];
        }
        self.reverseMap = [NSDictionary dictionaryWithContentsOfFile:mapPath];
    }
    return self.reverseMap;
}

**Comment by Insfgg99x** [comment]
你好，感谢你的建议，这个reverseString本身是可逆的互转。
你西药更新pod请在终端执行pod repo update 或者pod setup更新你的pod.
最新版1.1亲测可用，安装 "pod FGReverser", "~> 1.1"
请确保你安装的是1.1版本。

**Comment by Insfgg99x** [comment]
1.1才可以

**Comment by miku1958** [comment]
你好,我用的是1.1,1.1下[self mapper]拿到的一直是空的我才去看了一下

**Comment by Insfgg99x** [comment]
@miku1958 感谢你的反馈，已经确认问题存在！我会即可提交更新谢谢！

**Comment by Insfgg99x** [comment]
[release 2.0] 解决资源文件找不到的问题，并实现繁简互转统一一个方法，重命名转换方法。

**Comment by Insfgg99x** [comment]
pod  repo update
pod "FGReverser", "~> 2.0"
pod install
