### ISSUE TITLE
我想结合当前系统语言来实现转化,应该怎么弄?

### ISSUE THREAD

**Issue by ThymeBoy** [Insfgg99x/FGReverser#4]
比如说,当前系统语言是繁体,然后我不知道传进来的字符串是繁体还是简体,但是我只要输出的是繁体就好了.和您现在的设置有冲突,我觉得是不是应该提供下多个方法?

**Comment by Insfgg99x** [comment]
那可以用本地化啊，就不需要这个了

**Comment by ThymeBoy** [comment]
我现在的需求就是后台传给我的数据也是我自己去转简繁,所以本地不行(虽然我对这个设置也是一肚子难受)

**Comment by ThymeBoy** [comment]
你本地设置的时候是以繁体为key和以简体为key分别都在fg_mapper中添加了一个键值对.是不是把这两个分为两个字典,然后每个字典对应一个方法.我百度了下,判断字符串是简体还是繁体好像木有什么答案

**Comment by Insfgg99x** [comment]
可以的，

**Comment by ThymeBoy** [comment]
那,这个字典怎么分割呢 ,你可以帮我分割下吗,或者给我说下去哪里弄这些数据源我自己来弄.麻烦了

**Comment by ThymeBoy** [comment]
知道怎么处理了,麻烦了

**Comment by Insfgg99x** [comment]
这分开难啊

**Comment by ThymeBoy** [comment]
是的,分开发现,简体有繁体,繁体中有简体

**Comment by Insfgg99x** [comment]
这个问题先关了哈，老铁
